/*
 * One-shot: turn the seed workflow's journal into src/lib/seed/accounts.ts.
 *
 * Each account was generated then adversarially verified; the verified bundle is the one
 * we keep. Dates arrive as "days ago" integers and get emitted as daysAgo(n) calls against
 * the fixed anchor, so the committed seed is deterministic and readable.
 *
 * Usage: pnpm exec tsx scripts/assemble-seed.ts <path-to/journal.jsonl>
 */
import { readFileSync, writeFileSync } from "node:fs";

const journalPath = process.argv[2];
if (!journalPath) {
  console.error("usage: tsx scripts/assemble-seed.ts <journal.jsonl>");
  process.exit(1);
}

type Bundle = {
  account: {
    id: string;
    personaId: string;
    name: string;
    industry: string;
    arr: number;
    stage: string;
    priority: string;
    atRisk: boolean;
    nextStep: string;
    closeTarget: string;
    amName: string;
    lastTouchDaysAgo: number;
  };
  contacts: { id: string; name: string; title: string; relationship: string; sentiment: string }[];
  activities: {
    id: string;
    kind: string;
    summary: string;
    body: string;
    source: string;
    occurredDaysAgo: number;
  }[];
};

const lines = readFileSync(journalPath, "utf8").split("\n").filter(Boolean);

// Keep one bundle per account, preferring the verified (post-review) version.
const byId = new Map<string, { bundle: Bundle; verified: boolean }>();
for (const line of lines) {
  let ev: { type?: string; result?: { bundle?: Bundle; account?: unknown } };
  try {
    ev = JSON.parse(line);
  } catch {
    continue;
  }
  if (ev.type !== "result" || !ev.result) continue;
  const isVerify = Boolean(ev.result.bundle);
  const bundle = (isVerify ? ev.result.bundle : (ev.result.account ? ev.result : null)) as Bundle | null;
  if (!bundle?.account?.id) continue;
  const existing = byId.get(bundle.account.id);
  if (!existing || (isVerify && !existing.verified)) {
    byId.set(bundle.account.id, { bundle, verified: isVerify });
  }
}

const bundles = [...byId.values()]
  .map((v) => v.bundle)
  .sort((a, b) => a.account.personaId.localeCompare(b.account.personaId) || a.account.id.localeCompare(b.account.id));

// The casting args got HTML-escaped on the way into the workflow, so "&amp;" and friends
// rode along into the generated text — strip them back out here.
const unescapeHtml = (s: string) =>
  s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
const q = (s: string) => JSON.stringify(unescapeHtml(s));

const accountRows = bundles
  .map((b) => {
    const a = b.account;
    return `  { id: ${q(a.id)}, personaId: ${q(a.personaId)}, name: ${q(a.name)}, industry: ${q(a.industry)}, arr: ${a.arr}, stage: ${q(a.stage)}, priority: ${q(a.priority)}, atRisk: ${a.atRisk}, nextStep: ${q(a.nextStep)}, closeTarget: ${q(a.closeTarget)}, amName: ${q(a.amName)}, lastTouch: daysAgo(${a.lastTouchDaysAgo}) },`;
  })
  .join("\n");

const contactRows = bundles
  .flatMap((b) =>
    b.contacts.map(
      (c) =>
        `  { id: ${q(c.id)}, accountId: ${q(b.account.id)}, name: ${q(c.name)}, title: ${q(c.title)}, relationship: ${q(c.relationship)}, sentiment: ${q(c.sentiment)} },`,
    ),
  )
  .join("\n");

const activityRows = bundles
  .flatMap((b) =>
    b.activities.map(
      (act) =>
        `  { id: ${q(act.id)}, accountId: ${q(b.account.id)}, kind: ${q(act.kind)}, summary: ${q(act.summary)}, body: ${q(act.body)}, source: ${q(act.source)}, occurredAt: daysAgo(${act.occurredDaysAgo}) },`,
    ),
  )
  .join("\n");

const file = `import type { Account, Activity, Contact } from "@/db/schema";

// Generated by the seed workflow (24 accounts, each adversarially verified), then committed.
// Everything is dated relative to this fixed anchor so the seed is fully deterministic and
// this same data is the labeled ground truth the evals grade against.
export const SEED_ANCHOR = new Date("2026-07-14T09:00:00.000Z");

function daysAgo(n: number): Date {
  return new Date(SEED_ANCHOR.getTime() - n * 24 * 60 * 60 * 1000);
}

export const ACCOUNTS: Account[] = [
${accountRows}
];

export const CONTACTS: Contact[] = [
${contactRows}
];

export const ACTIVITIES: Activity[] = [
${activityRows}
];
`;

writeFileSync("src/lib/seed/accounts.ts", file);
console.error(
  `wrote src/lib/seed/accounts.ts — ${bundles.length} accounts, ${bundles.reduce((n, b) => n + b.contacts.length, 0)} contacts, ${bundles.reduce((n, b) => n + b.activities.length, 0)} activities`,
);
